app:
    resource: '@AppBundle/Controller/'
    type: annotation

users:
    type:     rest
    resource: AppBundle\Controller\UserController

films:
    type:     rest
    resource: AppBundle\Controller\FilmController
